## @section Docker image configuration
##

## YDB operator image
##
image:
  ## @param image.pullPolicy Operator container pull policy
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent
  ## @param image.repository Operator image repository
  repository: cr.yandex/yc/ydb-kubernetes-operator
  ## @param image.tag Operator image tag
  tag: 0.1.0

## @param imagePullSecrets Secrets to use for Docker registry access
## Secrets must be provided manually.
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
## Example:
## pullSecrets:
##   - myRegistryKeySecretName
##
imagePullSecrets: []

## @skip nameOverride
nameOverride: ""
## @skip fullnameOverride
fullnameOverride: ""

## @section Resource quotas
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  ## @param resources.limits The resource limits for Operator container
  ## Например:
  ## limits:
  ##    cpu: 250m
  ##    memory: 512Mi
  limits: {}
  ## @param resources.requests The requested resources for Operator container
  ## Например:
  ## requests:
  ##    cpu: 250m
  ##    memory: 256Mi
  requests: {}