apiVersion: ydb.tech/v1alpha1
kind: Database
metadata:
  name: database-sample
spec:
  image:
    name: cr.yandex/crpl7ipeu79oseqhcgn2/ydb-oss:master
  nodes: 6
  resources:
    containerResources:
      limits:
        cpu: 100m
    storageUnits:
      - count: 1
        unitKind: ssd
  storageClusterRef:
    name: storage-sample