apiVersion: ydb.tech/v1alpha1
kind: Database
metadata:
  name: database-sample
spec:
  image:
    name: cr.yandex/crptqonuodf51kdj7a7d/ydb:22.4.44
  nodes: 3
  resources:
    storageUnits:
      - count: 1
        unitKind: ssd
  storageClusterRef:
    name: storage-sample
