apiVersion: ydb.tech/v1alpha1
kind: Storage
metadata:
  name: storage-sample
spec:
  dataStore:
    - volumeMode: Block
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 80Gi
  version: 21.4.30
  nodes: 8
  erasure: block-4-2