apiVersion: ydb.tech/v1alpha1
kind: Database
metadata:
  name: database-minikube-sample
spec:
  image:
    name: cr.yandex/crptqonuodf51kdj7a7d/ydb:24.4.4.2
  nodes: 1
  domain: Root
  service:
    grpc:
      externalHost: localhost
  resources:
    storageUnits:
      - count: 1
        unitKind: ssd
  storageClusterRef:
    name: storage-minikube-sample
