apiVersion: ydb.tech/v1alpha1
kind: Database
metadata:
  name: database-minikube-sample
spec:
  image:
    name: cr.yandex/crpl7ipeu79oseqhcgn2/ydb-oss:master
  nodes: 1
  domain: Root
  resources:
    containerResources:
      limits:
        cpu: 500m
    storageUnits:
      - count: 1
        unitKind: ssd
  storageClusterRef:
    name: storage-minikube-sample