name: Smart checkout
description: When using pull_request_target, is capable of checking out user changes instead of base branch state.
runs:
  using: "composite"
  steps:
  - name: checkout-when-fork-source
    uses: actions/checkout@v3
    if: github.event.pull_request.head.sha != ''
    with:
        ref: ${{ github.event.pull_request.head.sha }}
  - name: checkout-when-this-repo-source
    uses: actions/checkout@v3
    if: github.event.pull_request.head.sha == ''
