apiVersion: ydb.tech/v1alpha1
kind: Database
metadata:
  name: database-kind-sample
spec:
  image:
    name: cr.yandex/crptqonuodf51kdj7a7d/ydb:24.4.4.2
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                  - storage-node
          topologyKey: "kubernetes.io/hostname"
  nodes: 3
  resources:
    storageUnits:
      - count: 1
        unitKind: ssd
  storageClusterRef:
    name: storage-kind-sample
