name: check-pr
on: 
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - 'docs/**'
    types:
      - 'opened'
      - 'synchronize'
      - 'reopened'
      - 'labeled'
jobs:
  check_if_test_running_allowed:
    runs-on: ubuntu-latest
    outputs:
      is_org_member: ${{ steps.check_if_org_member.outputs.is_org_member }}
    steps:
      - name: check_if_org_member
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          script: |
            const response = await github.rest.orgs.checkMembershipForUser({
              org: context.payload.organization.login,
              username: context.payload.pull_request.user.login
            });
            // How to interpret status code: 
            // https://docs.github.com/en/rest/orgs/members?apiVersion=2022-11-28#check-organization-membership-for-a-user
            console.log(response.status);
            core.setOutput('is_org_member', JSON.stringify(response.status == '204'));
            console.log(JSON.stringify(response.status == '204'));
      - name: debug
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          script: |
            console.log(steps.check_if_org_member.outputs);
      - name: comment-if-waiting-on-ok
        if: ${{ steps.check-if-org-member.outputs.is-org-member == 'false' }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Hi! Thank you for contributing!\nThe tests on this PR will run after a maintainer adds an `ok-to-test` label to this PR manually. Thank you for your patience!'
            });
  job-debug:
    runs-on: ubuntu-latest
    needs: 
      - check_if_test_running_allowed
    steps:
      - name: debug
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          script: |
            console.log(needs.check_if_test_running_allowed.outputs.is_org_member);
  run-tests:
    needs: 
      - check_if_test_running_allowed
    if: needs.check_if_test_running_allowed.outputs.is_org_member == 'true'
    uses: ./.github/workflows/run-tests.yml
    secrets: inherit
