name: tag
on:
  push:
    branches:
      - automate-tags
jobs:
  job1: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2          
    - uses: butlerlogic/action-autotag@stable
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        strategy: regex
        root: "./deploy/ydb-operator/Chart.yaml"
        regex_pattern: 'version:[\s]*(["]?[0-9\.]{3,}["]?)'
  echo-things:
    runs-on: ubuntu-latest
    needs: job1
    if: ${{ needs.job1.outputs.tagcreated == 'yes' }}
    steps:
    - uses: actions/checkout@v2          
    - run: |
        echo ${{ needs.job1.outputs }}
  unconditional:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - uses: actions/checkout@v2          
    - run: |
        echo ${{ needs.job1.outputs }}
