name: tag
on:
  push:
    branches:
      - automate-tags
jobs:
  tag-job: 
    runs-on: ubuntu-latest
    outputs:
      tagcreated: ${{steps.tag-step.outputs.tagcreated}}
    steps:
    - uses: actions/checkout@v2          
    - id: tag-step
      uses: butlerlogic/action-autotag@stable
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        strategy: regex
        root: "./deploy/ydb-operator/Chart.yaml"
        regex_pattern: 'version:[\s]*(["]?[0-9\.]{3,}["]?)'
  echo-things:
    runs-on: ubuntu-latest
    needs: tag-job
    if: ${{ needs.tag-job.outputs.tagcreated == 'yes' }}
    steps:
    - uses: actions/checkout@v2          
    - run: |
        echo ${{ needs.tag-job.outputs.tagcreated }}
